services:
    worker-1:
        image: ${APP_IMAGE}:${SOURCE_COMMIT:-latest}
        restart: unless-stopped
        environment:
            - LOG_CHANNEL=worker-1
        volumes: &volumes
            -   type: bind
                source: ${SERVER_VOLUME}/.env.local
                target: /var/www/html/.env.local
                read_only: true
            -   type: bind
                source: ${SERVER_VOLUME}/var/log
                target: /var/www/html/var/log
            -   type: bind
                source: ${SERVER_VOLUME}/files
                target: /var/www/html/files
            -   type: bind
                source: ${SERVER_VOLUME}/public/media
                target: /var/www/html/public/media
            -   type: bind
                source: ${SERVER_VOLUME}/public/theme
                target: /var/www/html/public/theme
            -   type: bind
                source: ${SERVER_VOLUME}/public/sitemap
                target: /var/www/html/public/sitemap
            -   type: bind
                source: ${SERVER_VOLUME}/public/thumbnail
                target: /var/www/html/public/thumbnail
        entrypoint: [ "php", "bin/console", "messenger:consume", "async", "low_priority", "--time-limit=300", "--memory-limit=512M" ]
    worker-2:
        image: ${APP_IMAGE}:${SOURCE_COMMIT:-latest}
        restart: unless-stopped
        environment:
            - LOG_CHANNEL=worker-2
        volumes: *volumes
        entrypoint: [ "php", "bin/console", "messenger:consume", "async", "low_priority", "--time-limit=300", "--memory-limit=512M" ]

    scheduler:
        image: ${APP_IMAGE}:${SOURCE_COMMIT:-latest}
        restart: unless-stopped
        environment:
            - LOG_CHANNEL=scheduler
        volumes: *volumes
        entrypoint: [ "php", "bin/console", "scheduled-task:run" ]

