framework:
    cache:
        app: cache.adapter.redis_tag_aware
        system: cache.adapter.redis_tag_aware
        default_redis_provider: '%env(string:REDIS_CACHE_URL)%'
    session:
        handler_id: "%env(string:REDIS_SESSION_URL)%"

parameters:
    env(REDIS_CACHE_URL): 'redis://redis:6379/0'
    env(REDIS_SESSION_URL): 'redis://redis:6379/0'