shopware:
    admin_worker:
        enable_admin_worker: true
        enable_notification_worker: true
        enable_queue_stats_worker: true
    mail:
        update_mail_variables_on_send: true

framework:
    session:
        handler_id: redis://redis:6379/0
    cache:
        # to deactivate redis caching for local testing, switch the following two to cache.adapter.array
        app: cache.adapter.redis_tag_aware
        system: cache.adapter.redis_tag_aware
        default_redis_provider: redis://redis:6379/1
