name: Build

on:
  pull_request: null
  push:
    branches:
      - trunk

jobs:
  build:
    name: Build
    uses: shopware/github-actions/.github/workflows/build-zip.yml@main
    with:
      extensionName: '${{ github.event.repository.name }}'
