name: PHP checks

on:
  pull_request:
    paths:
      - '**/*.php'
      - .github/workflows/php.yml
  push:
    paths:
      - '**/*.php'
    branches:
      - trunk
  workflow_dispatch: null
  schedule:
    - cron: '0 3 * * *'

jobs:
  codestyle_php:
    if: github.event_name != 'schedule'
    name: Codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: shopware/github-actions/cs-fixer@main
        with:
          rules: ''

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: shopware/github-actions/setup-extension@main
        with:
          extensionName: '${{ github.event.repository.name }}'
          shopwareVersion: '${{ matrix.shopware-version }}'
          install: true
          extraRepositories: |
            {
              "${{ github.event.repository.name }}": {
                "type": "path",
                "url": "custom/plugins/${{ github.event.repository.name }}",
                "symlink": true
              }
            }

      - name: Create phpstan.neon
        working-directory: 'custom/plugins/${{ github.event.repository.name }}'
        shell: bash
        run: >
          printf "parameters:\n  tmpDir:
          ${GITHUB_WORKSPACE}/var/phpstan\nincludes:\n  - phpstan.neon.dist" >
          phpstan.neon

      - name: PHPStan cache
        uses: actions/cache@v4
        with:
          path: '${{ github.workspace }}/var/phpstan'
          key: '${{ runner.OS }}-${{ github.repository }}-phpstan-${{ github.sha }}'
          restore-keys: |
            ${{ runner.OS }}-${{ github.repository }}-phpstan-

      - name: Build PHPStan Bootstrap
        shell: bash
        run: >-
          php
          ${GITHUB_WORKSPACE}/src/Core/DevOps/StaticAnalyze/phpstan-bootstrap.php

      - name: Run PHPStan
        shell: bash
        run: >
          composer -d custom/plugins/${{ github.event.repository.name }}
          dump-autoload --dev

          composer -d custom/plugins/${{ github.event.repository.name }} run
          phpstan

  phpunit:
    strategy:
      fail-fast: false
      matrix:
        shopware-version:
          - trunk
          - 6.6.x
    uses: shopware/github-actions/.github/workflows/phpunit.yml@main
    with:
      extensionName: '${{ github.event.repository.name }}'
      shopwareVersion: '${{ matrix.shopware-version }}'
      uploadCoverage: true
    secrets:
      codecovToken: '${{ secrets.CODECOV_TOKEN }}'
