name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      BEARER_PACKAGES_SHOPWARE:
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./shopware
          file: ./shopware/docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}.toLowerCase()/${{ github.event.repository.name }}.toLowerCase():${{ inputs.environment }}
          build-args: |
            SHOPWARE_PACKAGES_TOKEN=${{ secrets.BEARER_PACKAGES_SHOPWARE }}
            SHOPWARE_CLI_FORCE_BUN=1 